services:
 product-service:
   image: product-jwt
   build: .
   container_name: productrest_con
   ports:
     - 8082:8081
   depends_on: 
     mysqlservice:
       condition: service_healthy  
   networks: 
     - prod_network
 
 mysqlservice:
   image: mysql:8
   container_name: sqlcontainer
   ports:
   - 3307:3306
   environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productkart
   healthcheck:
         test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
         interval: 10s
         timeout: 5s
         retries: 5
   networks: 
     - prod_network
 
networks:
  prod_network:
  
  
 